from node:18 
#linux os + nodejs

WORKDIR /app

COPY package.json ./   
#for both package*.json ./
COPY package-lock.json ./

RUN npm install

COPY server.js ./

EXPOSE 3000

CMD [ "node","server.js" ]